[package]
name = "cookie-odyssey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
config = { version = "0.14.0", features = [] }
dotenv = "0.15.0"
sea-orm = { version = "0.12.15", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros", "with-uuid"] }
serde = { version = "1.0.200", features = ["derive"] }
tera = "1.19.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
