[package]
name = "cookie-odyssey"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
app-config = { path = "config" }
axum = "0.7.5"
chrono = { workspace = true }
entities = { path = "entities" }
migration = { path = "migration"}
object_store = { version = "0.10.0", features = ["aws"] }
sea-orm = { workspace = true }
serde = { workspace = true }
tera = { version = "1.19.1" }
thiserror = { workspace = true }
tokio = { version = "1.37.0", features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.18" }
url = { workspace = true }

[workspace]
members = ["config", "entities", "migration"]

[workspace.dependencies]
anyhow = "1.0.83"
chrono = { version = "0.4.38", features = ["std", "clock"] }
sea-orm = { version = "0.12.15", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros", "with-uuid"] }
serde = { version = "1.0.200", features = ["derive"] }
thiserror = { version = "1.0.60" }
tracing = { version = "0.1.40" }
url = "2.5.0"
