version: "3.8"

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - "./data/azurite:/data mcr.microsoft.com/azure-storage/azurite"
