//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "file")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub bucket: String,
    pub key: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::journal::Entity")]
    Journal,
    #[sea_orm(has_many = "super::video_transcode_task::Entity")]
    VideoTranscodeTask,
}

impl Related<super::journal::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Journal.def()
    }
}

impl Related<super::video_transcode_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoTranscodeTask.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
