//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "journal_entry")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub journal_id: i32,
    #[sea_orm(column_type = "Text")]
    pub date: String,
    #[sea_orm(column_type = "Text")]
    pub time: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    pub draft: bool,
    #[sea_orm(column_type = "Text")]
    pub address: String,
    pub lat: Option<Decimal>,
    pub lng: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::journal::Entity",
        from = "Column::JournalId",
        to = "super::journal::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Journal,
    #[sea_orm(has_many = "super::journal_entry_media::Entity")]
    JournalEntryMedia,
}

impl Related<super::journal::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Journal.def()
    }
}

impl Related<super::journal_entry_media::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JournalEntryMedia.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
