//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::file::Entity as File;
pub use super::journal::Entity as Journal;
pub use super::journal_comment::Entity as JournalComment;
pub use super::journal_entry::Entity as JournalEntry;
pub use super::journal_entry_media::Entity as JournalEntryMedia;
pub use super::user::Entity as User;
pub use super::video_transcode_task::Entity as VideoTranscodeTask;
