//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::file::Entity as File;
pub use super::journal::Entity as Journal;
pub use super::journal_entry::Entity as JournalEntry;
pub use super::journal_entry_media::Entity as JournalEntryMedia;
pub use super::user::Entity as User;
