name: CI

on:
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-rust:
    runs-on: ubuntu-latest

    steps:
      - uses: extractions/setup-just@v3
        with:
          just-version: 1.40.0

      - uses: actions/checkout@v4

      - run: just lint-rust

  lint-js:
    runs-on: ubuntu-latest

    steps:
      - uses: extractions/setup-just@v3
        with:
          just-version: 1.40.0

      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions

      - run: bun install
      - run: bun install
        working-directory: migration/data-migrations/journal-entry-media-width-height-thumbnail

      - run: just lint-js
